name: Docker Image CI

on:
  push:
    branches:
    - main
    paths-ignore:
    - ".vscode/**"
    - docs
    - test
    - .env.sample
    - README.md
    - docker-compose.yml
jobs:

  build:

    runs-on: [ubuntu-latest]
    environment: docker-ci

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    -
      name: Build and push api
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: iyjian/snapshot:latest
    - run: curl --data-urlencode "content=image snapshot build successfully" https://h.tltr.top/g/OrvXSVI
